apiVersion: v1
data:
  API_BASE_PATH: "/api-v1"
  DATABASE_ERROR_DELAY: "5000"
  DB_DATABASE: perform
  DB_MODE: production
  FAVICON: src/server/public/favicon.ico
  GOOGLE_APPLICATION_CREDENTIALS: ./certs/gcpStorage/gcpStorageKey.json
  HOST: http://localhost
  NODE_ENV: production
  NODE_MODULES_PATH: node_modules
  OPENAPI_FILE: api/openapi.json
  PORT: "8080"
  STATIC_TEST_PATH: src/test/client-static
  SVR_LISTEN_TIMEOUT: "3"
  SVR_LISTEN_TRIES: "3"
  VERSION: v1.0.0
kind: ConfigMap
metadata:
  name: {{ include "pp-chart.fullname" . -}}{{- .Values.configmap.nameTag }}
  namespace: default
